// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

RWStructuredBuffer<float> beta;
RWStructuredBuffer<float> rho1;
RWByteAddressBuffer rho;

bool first;

[numthreads(1,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    beta[0] = 0;
    if (first == false)
    {
        beta[0] = asfloat(rho.Load(0)) / rho1[0];
    }
    rho1[0] = asfloat(rho.Load(0));

    rho.Store(0, asuint(0));
}
